#!/bin/bash

# Debian Linux System Backup Skript
#
# Sichert Konfiguration, Systemeinstellungen und Daten lokal
# und stellt sie zur Abholung in Verzeichnis $DIRECTORY bereit
#
# dj0Nz Oct 2021

# Variablen definieren
TMPDIRECTORY=/var/tmp/backup
DIRECTORY=/root/backup
LCNAME=`/bin/hostname -s | tr '[:upper:]' '[:lower:]'`

# Saubere Backup-Verzeichnisse erzeugen
if [ -d $TMPDIRECTORY ]; then
   rm -r $TMPDIRECTORY
fi
mkdir $TMPDIRECTORY
if [ -d $DIRECTORY ]; then
   rm $DIRECTORY/* > /dev/null 2>&1
else
   mkdir $DIRECTORY
fi

# Versionsinformationen und manuell installierte Pakete
cat /etc/os-release > $TMPDIRECTORY/debian-version.txt
grep -oP "Unpacking \K[^: ]+" /var/log/installer/syslog | sort -u | comm -13 /dev/stdin <(apt-mark showmanual | sort) > $TMPDIRECTORY/debian-pkg-list.txt

# Systemspezifische Dinge und Root-Home sichern.
tar cPf $TMPDIRECTORY/etc.tar /etc/ > /dev/null 2>&1
tar cPf $TMPDIRECTORY/root.tar /root/ > /dev/null 2>&1
tar cPf $TMPDIRECTORY/home.tar /home/ > /dev/null 2>&1
tar cPf $TMPDIRECTORY/cron.tar /var/spool/cron/ > /dev/null 2>&1

# PVE spezifische Dinge sichern
pveversion -v > $TMPDIRECTORY/pve-version.txt
tar cPf $TMPDIRECTORY/pve.tar /var/lib/pve* > /dev/null 2>&1

# Backup File und Prüfsumme in Download-Verzeichnis bereit stellen
tar cfz $DIRECTORY/$LCNAME.tgz $TMPDIRECTORY/* > /dev/null 2>&1
cd $DIRECTORY
md5sum $LCNAME.tgz > $LCNAME.md5

# Ende
